### PR TITLE
tmux_env.py: support python 3.x and fixes

### PR DESCRIPTION
**Pull request by dobbymoodge**
This commit replaces a `dict.iteritems()` call with the correct
`dict.items()` call. It also adds the `text=True` arg to the
`subprocess.check_output` call so the output can be handled as a
`str`. Other changes include minor formatting tweaks and replacing a
`+`-style string concatenation with "f-string" style string
formatting.

These changes most likely break Python 2.x compatibility

### CODE REVIEW

**Comment by dobbymoodge** [comment]
@agriffis I was preparing a fix for the downstream [scripts repo](https://github.com/weechat/scripts/blob/master/python/tmux_env.py) (see the PR branch at https://github.com/dobbymoodge/scripts/tree/tmux_env-py3), but figured you might appreciate a PR against your source repo first. IMHO we shouldn't try to preserve Python 2.x compatibility, but I'm interested in your input. Tweaking the changes to work on both should be pretty straightforward, if you think we should bother.

**Comment by agriffis** [comment]
@dobbymoodge Thanks! I haven't used weechat in a long time, so I'm not sure of the best course. Do you think I should archive this repo so that the scripts repo becomes canonical, or is there some value to keeping the upstream repo alive? In that case I could make you a maintainer. What do you think?

**Comment by dobbymoodge** [comment]
I don't want to be the designated maintainer, so I think it's reasonable to make the `weechat/scripts` repo canonical. Maybe update the `README` before you archive it to make it clear what's up. :)

Thanks for the quick response btw! Curious; did you switch IRC clients -if so, to which one - or have you stopped using IRC?

**Comment by agriffis** [comment]
Sounds good. I'll put something in the README and then use the official GitHub process for archiving a repo: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-archiving-repositories

Regarding IRC, I don't use it much these days. Most of my chat is on Keybase or Gitter.

**Pull request closed without merging**
